### ISSUE TITLE
add all supported properties to README

### ISSUE THREAD

**Issue by awinogradov** [theprotein/shortcss#6]

**Comment by qfox** [comment]
https://github.com/gilmoreorless/css-shorthand-properties/blob/master/index.js He it is.

**Comment by awinogradov** [comment]
@zxqfox добавь линк)

**Comment by qfox** [comment]
Так в ридми же есть ссылка на этот проект

**Comment by qfox** [comment]
![image](https://cloud.githubusercontent.com/assets/677518/8409700/4f22959e-1e82-11e5-8875-74641c5ef1f1.png)

**Comment by awinogradov** [comment]
вот ты ленивый)
